SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `CATEGORY` (
  `ID` int NOT NULL,
  `NAME` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `CODE` varchar(8) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

CREATE TABLE `PRODUCT` (
  `ID` int NOT NULL,
  `CODE` varchar(255) COLLATE latin1_general_cs DEFAULT NULL,
  `DESCRIPTION` varchar(255) COLLATE latin1_general_cs DEFAULT NULL,
  `NAME` varchar(255) COLLATE latin1_general_cs DEFAULT NULL,
  `PRICE` decimal(19,2) DEFAULT NULL,
  `CATEGORY_ID` int DEFAULT NULL,
  `SUPPLIER_ID` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

CREATE TABLE `STOCK` (
  `ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  `PRODUCT_ID` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

CREATE TABLE `SUPPLIER` (
  `ID` int NOT NULL,
  `ADDRESS` varchar(255) COLLATE latin1_general_cs DEFAULT NULL,
  `PHONE` varchar(255) COLLATE latin1_general_cs DEFAULT NULL,
  `NAME` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `CODE` varchar(8) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;


ALTER TABLE `CATEGORY`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `uq_category_code` (`CODE`);

ALTER TABLE `PRODUCT`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Uq_product_code` (`CODE`),
  ADD KEY `fk_category_id` (`CATEGORY_ID`),
  ADD KEY `fk_supplier_id` (`SUPPLIER_ID`);

ALTER TABLE `STOCK`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `fk_product_id` (`PRODUCT_ID`);

ALTER TABLE `SUPPLIER`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `uq_supplier_code` (`CODE`);


ALTER TABLE `CATEGORY`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `PRODUCT`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `STOCK`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `SUPPLIER`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT;


ALTER TABLE `PRODUCT`
  ADD CONSTRAINT `fk_category_id` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`),
  ADD CONSTRAINT `fk_supplier_id` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `SUPPLIER` (`ID`);

ALTER TABLE `STOCK`
  ADD CONSTRAINT `fk_product_id` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`);
COMMIT;
